server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      
allowedOrigins: "http://localhost:3000" 

---
logging:
  level: DEBUG
  loggers:
    com.christianquah: DEBUG

    
