server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      


---
logging:
  level: DEBUG
  loggers:
    com.christianquah: DEBUG

    
allowedOrigins: "http://localhost:3000"